### ISSUE TITLE
[bug]: Workflow never executes

### ISSUE THREAD

**Issue by igorbeslic** [bytechefhq/bytechef#1288]
### Feature, functionality or component that stop working

JobSyncExecutor doesn't execute workflow if server is ran in PROD profile.
Only way to revive job execution engine is restarting server. Shutting down server results in error stacktrace that refers to job executor:
```java
Disconnected from the target VM, address: '127.0.0.1:62683', transport: 'socket'
2024-07-30T23:05:51.952+02:00  INFO 88064 --- [ionShutdownHook] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler_$_NON_CLUSTERED paused. 
2024-07-30T23:06:51.976+02:00 ERROR 88064 --- [nio-8080-exec-3] com.bytechef.atlas.worker.TaskWorker     : null 

java.lang.InterruptedException: null
	at java.base/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:471)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:203)
	at com.bytechef.atlas.worker.TaskWorker.onTaskExecutionEvent(TaskWorker.java:133)
	at com.bytechef.atlas.sync.executor.JobSyncExecutor.lambda$new$1(JobSyncExecutor.java:139)
	at com.bytechef.message.broker.sync.SyncMessageBroker.send(SyncMessageBroker.java:57)
	at com.bytechef.atlas.sync.executor.JobSyncExecutor.lambda$createEventPublisher$6(JobSyncExecutor.java:190)
	at com.bytechef.atlas.coordinator.task.dispatcher.DefaultTaskDispatcher.dispatch(DefaultTaskDispatcher.java:65)
	at com.bytechef.atlas.coordinator.task.dispatcher.DefaultTaskDispatcher.dispatch(DefaultTaskDispatcher.java:35)
	at com.bytechef.atlas.coordinator.task.dispatcher.TaskDispatcherChain.dispatch(TaskDispatcherChain.java:42)
	at com.bytechef.atlas.coordinator.job.JobExecutor.executeNextTask(JobExecutor.java:92)
	at com.bytechef.atlas.coordinator.job.JobExecutor.execute(JobExecutor.java:72)
	at com.bytechef.atlas.coordinator.TaskCoordinator.onStartJobEvent(TaskCoordinator.java:145)
	at com.bytechef.atlas.sync.executor.JobSyncExecutor.lambda$new$5(JobSyncExecutor.java:174)
	at com.bytechef.message.broker.sync.SyncMessageBroker.send(SyncMessageBroker.java:57)
	at com.bytechef.atlas.sync.executor.JobSyncExecutor.lambda$createEventPublisher$6(JobSyncExecutor.java:190)
	at com.bytechef.atlas.execution.facade.JobFacadeImpl.createJob(JobFacadeImpl.java:83)
	at com.bytechef.atlas.sync.executor.JobSyncExecutor.execute(JobSyncExecutor.java:178)
	at com.bytechef.platform.workflow.test.executor.JobTestExecutor.execute(JobTestExecutor.java:63)
	at com.bytechef.platform.workflow.test.facade.WorkflowTestFacadeImpl.testWorkflow(WorkflowTestFacadeImpl.java:143)
	at com.bytechef.platform.workflow.test.web.rest.WorkflowTestApiController.testWorkflow(WorkflowTestApiController.java:46)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:174)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at com.bytechef.platform.workflow.test.web.rest.WorkflowTestApiController$$SpringCGLIB$$0.testWorkflow(<generated>)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108)
	at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231)
	at org.springframework.security.web.ObservationFilterChainDecorator$FilterObservation$SimpleFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:479)
	at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:340)
	at org.springframework.security.web.ObservationFilterChainDecorator.lambda$wrapSecured$0(ObservationFilterChainDecorator.java:82)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:128)
	at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:110)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at com.bytechef.security.web.filter.CookieCsrfFilter.doFilterInternal(CookieCsrfFilter.java:45)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at com.bytechef.security.web.filter.SpaWebFilter.doFilterInternal(SpaWebFilter.java:59)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:131)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$0(ObservationFilterChainDecorator.java:323)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:224)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
	at org.springframework.web.servlet.handler.HandlerMappingIntrospector.lambda$createCacheFilter$3(HandlerMappingIntrospector.java:195)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
	at org.springframework.security.config.annotation.web.configuration.WebMvcSecurityConfiguration$CompositeFilterChainProxy.doFilter(WebMvcSecurityConfiguration.java:230)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:107)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:904)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1583)

2024-07-30T23:06:51.981+02:00 ERROR 88064 --- [nio-8080-exec-3] c.b.atlas.sync.executor.JobSyncExecutor  : null 
2024-07-30T23:06:57.125+02:00 ERROR 88064 --- [rver-app-task-1] com.bytechef.atlas.worker.TaskWorker     : null 

java.lang.InterruptedException: null
	at java.base/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:471)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:203)
	at com.bytechef.atlas.worker.TaskWorker.onTaskExecutionEvent(TaskWorker.java:133)
	at com.bytechef.atlas.sync.executor.JobSyncExecutor.lambda$new$1(JobSyncExecutor.java:139)
	at com.bytechef.message.broker.sync.SyncMessageBroker.send(SyncMessageBroker.java:57)
	at com.bytechef.atlas.sync.executor.JobSyncExecutor.lambda$createEventPublisher$6(JobSyncExecutor.java:190)
	at com.bytechef.atlas.coordinator.task.dispatcher.DefaultTaskDispatcher.dispatch(DefaultTaskDispatcher.java:65)
	at com.bytechef.atlas.coordinator.task.dispatcher.DefaultTaskDispatcher.dispatch(DefaultTaskDispatcher.java:35)
	at com.bytechef.atlas.coordinator.task.dispatcher.TaskDispatcherChain.dispatch(TaskDispatcherChain.java:42)
	at com.bytechef.task.dispatcher.loop.LoopTaskDispatcher.dispatch(LoopTaskDispatcher.java:120)
	at com.bytechef.task.dispatcher.loop.LoopTaskDispatcher.dispatch(LoopTaskDispatcher.java:54)
	at com.bytechef.atlas.coordinator.task.dispatcher.TaskDispatcherChain.dispatch(TaskDispatcherChain.java:42)
	at com.bytechef.atlas.coordinator.job.JobExecutor.executeNextTask(JobExecutor.java:92)
	at com.bytechef.atlas.coordinator.job.JobExecutor.execute(JobExecutor.java:72)
	at com.bytechef.atlas.coordinator.task.completion.DefaultTaskCompletionHandler.handle(DefaultTaskCompletionHandler.java:124)
	at com.bytechef.atlas.coordinator.task.completion.TaskCompletionHandlerChain.handle(TaskCompletionHandlerChain.java:36)
	at com.bytechef.atlas.coordinator.TaskCoordinator.onTaskExecutionCompleteEvent(TaskCoordinator.java:206)
	at com.bytechef.atlas.sync.executor.JobSyncExecutor.lambda$new$4(JobSyncExecutor.java:172)
	at com.bytechef.message.broker.sync.SyncMessageBroker.send(SyncMessageBroker.java:57)
	at com.bytechef.atlas.sync.executor.JobSyncExecutor.lambda$createEventPublisher$6(JobSyncExecutor.java:190)
	at com.bytechef.atlas.worker.TaskWorker.lambda$onTaskExecutionEvent$0(TaskWorker.java:113)
	at com.bytechef.async.config.AsyncConfiguration$TenantThreadPoolTaskExecutor.lambda$getTenantRunnable$0(AsyncConfiguration.java:111)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

2024-07-30T23:06:57.125+02:00 ERROR 88064 --- [rver-app-task-2] com.bytechef.atlas.worker.TaskWorker     : null 

java.lang.InterruptedException: null
	at java.base/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:471)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:203)
	at com.bytechef.atlas.worker.TaskWorker.onTaskExecutionEvent(TaskWorker.java:133)
	at com.bytechef.atlas.sync.executor.JobSyncExecutor.lambda$new$1(JobSyncExecutor.java:139)
	at com.bytechef.message.broker.sync.SyncMessageBroker.send(SyncMessageBroker.java:57)
	at com.bytechef.atlas.sync.executor.JobSyncExecutor.lambda$createEventPublisher$6(JobSyncExecutor.java:190)
	at com.bytechef.atlas.coordinator.task.dispatcher.DefaultTaskDispatcher.dispatch(DefaultTaskDispatcher.java:65)
	at com.bytechef.atlas.coordinator.task.dispatcher.DefaultTaskDispatcher.dispatch(DefaultTaskDispatcher.java:35)
	at com.bytechef.atlas.coordinator.task.dispatcher.TaskDispatcherChain.dispatch(TaskDispatcherChain.java:42)
	at com.bytechef.atlas.coordinator.job.JobExecutor.executeNextTask(JobExecutor.java:92)
	at com.bytechef.atlas.coordinator.job.JobExecutor.execute(JobExecutor.java:72)
	at com.bytechef.atlas.coordinator.task.completion.DefaultTaskCompletionHandler.handle(DefaultTaskCompletionHandler.java:124)
	at com.bytechef.atlas.coordinator.task.completion.TaskCompletionHandlerChain.handle(TaskCompletionHandlerChain.java:36)
	at com.bytechef.atlas.coordinator.TaskCoordinator.onTaskExecutionCompleteEvent(TaskCoordinator.java:206)
	at com.bytechef.atlas.sync.executor.JobSyncExecutor.lambda$new$4(JobSyncExecutor.java:172)
	at com.bytechef.message.broker.sync.SyncMessageBroker.send(SyncMessageBroker.java:57)
	at com.bytechef.atlas.sync.executor.JobSyncExecutor.lambda$createEventPublisher$6(JobSyncExecutor.java:190)
	at com.bytechef.atlas.worker.TaskWorker.lambda$onTaskExecutionEvent$0(TaskWorker.java:113)
	at com.bytechef.async.config.AsyncConfiguration$TenantThreadPoolTaskExecutor.lambda$getTenantRunnable$0(AsyncConfiguration.java:111)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

2024-07-30T23:06:57.126+02:00 ERROR 88064 --- [rver-app-task-2] c.b.atlas.sync.executor.JobSyncExecutor  : null 
2024-07-30T23:06:57.126+02:00 ERROR 88064 --- [rver-app-task-1] c.b.atlas.sync.executor.JobSyncExecutor  : null 
2024-07-30T23:06:57.129+02:00  INFO 88064 --- [ionShutdownHook] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler_$_NON_CLUSTERED shutting down. 
2024-07-30T23:06:57.129+02:00  INFO 88064 --- [ionShutdownHook] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler_$_NON_CLUSTERED paused. 
2024-07-30T23:06:57.129+02:00  INFO 88064 --- [ionShutdownHook] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler_$_NON_CLUSTERED shutdown complete. 

Process finished with exit code 130 (interrupted by signal 2:SIGINT)

``` 

### Steps To Reproduce

active profiles: prod,api-docs,local
- create Postgres Database significant_bits
- create default public schema
- create table CITY 
- in Demo project import workflow
- try to run workflow - add PostgreSQL connection and click Play icon. There is spinner at the bottom of the page where output should appear. If you try to click stop icon nothing happens
- publish project
- create test project instance
- try to run workflow manually - same
- shutdown application - there is stacktrace after couple minutes (graceful shutdown period for threads)

Workflow:
```javascript
{
    "label": "Read CSV and send to DB",
    "description": "Read text file lines where data is separated by comma character.",
    "inputs": [],
    "triggers": [
        {
            "label": "Manual",
            "name": "manual",
            "type": "manual/v1/manual"
        }
    ],
    "tasks": [
        {
            "label": "Filesystem",
            "name": "filesystem_1",
            "parameters": {
                "filename": "/Users/user/dev/bytechef/mount_to_docker/cities.csv"
            },
            "type": "filesystem/v1/readFile",
            "description": "Files at local machine where ByteChef Self Hosted docker image is running. Folder is configured with environment variable.",
            "metadata": {
                "ui": {
                    "dynamicPropertyTypes": {}
                }
            }
        },
        {
            "label": "CSV File",
            "name": "csvFile_1",
            "parameters": {
                "delimiter": ",",
                "headerRow": true,
                "includeEmptyCells": false,
                "readAsString": false,
                "fileEntry": "${filesystem_1}"
            },
            "type": "csvFile/v1/read",
            "description": "Interface to physical file configured by Filesystem component.",
            "metadata": {
                "ui": {
                    "dynamicPropertyTypes": {}
                }
            }
        },
        {
            "type": "loop/v1",
            "name": "loop_1",
            "parameters": {
                "items": "${csvFile_1}",
                "iteratee": [
                    {
                        "label": "Log",
                        "name": "logEntry1",
                        "parameters": {
                            "text": "Linija: ${loop_1.item} city: ${loop_1.item[8]}"
                        },
                        "type": "logger/v1/info"
                    },
                    {
                        "label": "PostgreSQL",
                        "name": "postgresql_1",
                        "type": "postgresql/v1/insert",
                        "parameters": {
                            "schema": "public",
                            "table": "CITY",
                            "columns": [
                                "${loop_1.item[8]}",
                                "${loop_1.item[9]}"
                            ]
                        },
                        "metadata": {
                            "ui": {
                                "dynamicPropertyTypes": {
                                    "columns[0]": "STRING",
                                    "columns[1]": "STRING"
                                }
                            }
                        }
                    }
                ]
            }
        },
        {
            "label": "PostgreSQL_2",
            "name": "postgresql_2",
            "parameters": {},
            "type": "postgresql/v1/query"
        }
    ]
}
``` 

### Last Known Working Marker

75a52b8498838b236fbf7f8d0b0d46561614a214

### Marker at which regression starts

324279c2622130ae6b61883201ca2727b6f74b8c

### OS

MacOsX

### Browser

Chrome

**Comment by ivicac** [comment]
Fixed
