### ISSUE TITLE
[regression]: OpenAI Component Can Not Generate Image

### ISSUE THREAD

**Issue by igorbeslic** [bytechefhq/bytechef#1321]
### Feature, functionality or component that stop working

After changes on OpenAI component properties it is not possible to generate image any more.

### Steps To Reproduce

Flow described here does not work
https://guidejar.com/guides/af71da94-9c51-4859-a89f-6f20d14081be
there is error stacktrace in the bytechef log:
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1767)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1541)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1446)
	at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:958)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:1441)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:48)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
	
```  

### Last Known Working Marker

e436ef76b5983d14617e65fddeb55b07fe1e0564

### Marker at which regression starts

7d91a6b6f451957fe7e03edd0ca6e28f1fd5b180

### OS

MacOsX

### Browser

Chrome

**Comment by igorbeslic** [comment]
com.theokanning.openai.OpenAiHttpException: Billing hard limit has been reached

Catch exception and throw provider exception

**Comment by igorbeslic** [comment]
Parameter n=1 transforms to NULL -> we rely to UI to pick defaults but seems it is not the case... It is much better that backend provides defaults.
PROBLEM: we won't spot UI bugs if backend silently fixes errors... We might send message to UI that some property wasn't set and backend set it to the default.

**Comment by igorbeslic** [comment]
Timeout should be configurable, 10s is default... particular request for image can last longer...
